/**
 * Injection tokens for dependency injection
 */
export const TOKENS = {
  MESSAGE_QUEUE_SERVICE: 'MESSAGE_QUEUE_SERVICE',
  INGESTION_SERVICE: 'INGESTION_SERVICE',
  TEXTRACT_SERVICE: 'TEXTRACT_SERVICE',
  TEXTRACT_NOTIFICATION_SERVICE: 'TEXTRACT_NOTIFICATION_SERVICE',
}; 